const Data = [
    {
        id: "1",
        movieName: "Prey for the Devil",
        imgSrc: "https://image.tmdb.org/t/p/w300/w3s6XEDNVGq5LUlghqs6VlvsvL6.jpg",
        releaseDate: "2022-10-23",
        aboutMovie: "In response to a global rise in demonic possessions, the Catholic Church reopens exorcism schools to train priests in the Rite of Exorcism. On this spiritual battlefield, an unlikely warrior rises: a young nun, Sister Ann. Thrust onto the spiritual frontline with fellow student Father Dante, Sister Ann finds herself in a battle for the soul of a young girl and soon realizes the Devil has her right where he wants her.",
        movieCategory: "Thriller",
    },
    {
        id: "2",
        movieName: "Guillermo del Toro's Pinocchio",
        imgSrc: "https://image.tmdb.org/t/p/w300/vx1u0uwxdlhV2MUzj4VlcMB0N6m.jpg",
        releaseDate: "2022-11-09",
        aboutMovie: "During the rise of fascism in Mussolini's Italy, a wooden boy brought magically to life struggles to live up to his father's expectations.",
        movieCategory: "Action",
    },
    {
        id: "3",
        movieName: "Violent Night",
        imgSrc: "https://image.tmdb.org/t/p/w300/1XSYOP0JjjyMz1irihvWywro82r.jpg",
        releaseDate: "2022-11-30",
        aboutMovie: "When a team of mercenaries breaks into a wealthy family compound on Christmas Eve, taking everyone inside hostage, the team isn't prepared for a surprise combatant: Santa Claus is on the grounds, and he's about to show why this Nick is no saint",
        movieCategory: "Thriller",
    },
    {
        id: "4",
        movieName: "Avatar: The Way of Water",
        imgSrc: "https://image.tmdb.org/t/p/w300/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
        releaseDate: "2022-12-14",
        aboutMovie: "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
        movieCategory: "Family",
    },
    {
        id: "5",
        movieName: "Savage Salvation",
        imgSrc: "https://image.tmdb.org/t/p/w300/fJRt3mmZEvf8gQzoNLzjPtWpc9o.jpg",
        releaseDate: "2022-12-02",
        aboutMovie: "Newly engaged Shelby John and Ruby Red want a fresh start after their struggles with addiction, but when Shelby discovers his beloved Ruby dead on their porch, he embarks on a vengeful killing spree of the dealers who supplied her. Armed with nothing but adrenaline and a nail gun, Shelby begins to unleash chaos on the town's criminal underbelly, as he hunt's down crime lord Coyote. Sheriff Church must race against the clock to put an end to Shelby's vigilante justice before the entire town descends into a bloodbath.",
        movieCategory: "Action",
    },
    {
        id: "6",
        movieName: "Avatar",
        imgSrc: "https://image.tmdb.org/t/p/w300/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
        releaseDate: "2009-12-15",
        aboutMovie: "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
        movieCategory: "Family",
    },
    {
        id: "7",
        movieName: "Black Adam",
        imgSrc: "https://image.tmdb.org/t/p/w300/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
        releaseDate: "2022-10-19",
        aboutMovie: "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
        movieCategory: "Family",
    },
    {
        id: "8",
        movieName: "Love, Rosie",
        imgSrc: "https://image.tmdb.org/t/p/w300/rpD0t7DhzJVadnzgxSYrqljQTL2.jpg",
        releaseDate: "2022-11-09",
        aboutMovie: "QSince the moment they met at age 5, Rosie and Alex have been best friends, facing the highs and lows of growing up side by side. A fleeting shared moment, one missed opportunity, and the decisions that follow send their lives in completely different directions. As each navigates the complexities of life, love, and everything in between, they always find their way back to each other - but is it just friendship, or something more?",
        movieCategory: "Love",
    },
    {
        id: "9",
        movieName: "Redeeming Love",
        imgSrc: "https://image.tmdb.org/t/p/w300/pDc2HxQtC0MlKD4QfRvmKREEyhc.jpg",
        releaseDate: "2022-01-21",
        aboutMovie: "A retelling of the biblical book of Hosea set against the backdrop of the California Gold Rush of 1850.",
        movieCategory: "Love",
    },
    {
        id: "10",
        movieName: "R.I.P.D. 2: Rise of the Damned",
        imgSrc: "https://image.tmdb.org/t/p/w300/eeUNWsdoiOijOZAMaWFDA5Pb1n8.jpg",
        releaseDate: "2022-09-08",
        aboutMovie: "The story of 14th century Czech icon and warlord Jan Zizka who defeated armies of the Teutonic Order and the Holy Roman Empire.",
        movieCategory: "Action",
    },
    {
        id: "11",
        movieName: "The Woman King",
        imgSrc: "https://image.tmdb.org/t/p/w300/438QXt1E3WJWb3PqNniK0tAE5c1.jpg",
        releaseDate: "2022-09-15",
        aboutMovie: "The story of the Agojie, the all-female unit of warriors who protected the African Kingdom of Dahomey in the 1800s with skills and a fierceness unlike anything the world has ever seen, and General Nanisca as she trains the next generation of recruits and readies them for battle against an enemy determined to destroy their way of life.",
        movieCategory: "Action",
    },
    {
        id: "12",
        movieName: "Black Panther: Wakanda Forever",
        imgSrc: "https://image.tmdb.org/t/p/w300/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
        releaseDate: "2022-11-09",
        aboutMovie: "Queen Ramonda, Shuri, M'Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T'Challa's death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
        movieCategory: "Action",
    },
    {
        id: "13",
        movieName: "Emancipation",
        imgSrc: "https://image.tmdb.org/t/p/w300/s9sUK1vAaOcxJfKzNTszrNkPhkH.jpg",
        releaseDate: "2022-12-02",
        aboutMovie: "Inspired by the gripping true story of a man who would do anything for his family—and for freedom. When Peter, an enslaved man, risks his life to escape and return to his family, he embarks on a perilous journey of love and endurance",
        movieCategory: "Action",
    },
    {
        id: "14",
        movieName: "R.I.P.D. 2: Rise of the Damned",
        imgSrc: "https://image.tmdb.org/t/p/w300/g4yJTzMtOBUTAR2Qnmj8TYIcFVq.jpg",
        releaseDate: "2022-11-15",
        aboutMovie: "When Sheriff Roy Pulsipher finds himself in the afterlife, he joins a special police force and returns to Earth to save humanity from the undead.",
        movieCategory: "Action",
    },
    {
        id: "15",
        movieName: "Love Actually",
        imgSrc: "https://image.tmdb.org/t/p/w300/7QPeVsr9rcFU9Gl90yg0gTOTpVv.jpg",
        releaseDate: "2003-09-07",
        aboutMovie: "Eight London couples try to deal with their relationships in different ways. Their tryst with love makes them discover how complicated relationships can be.",
        movieCategory: "Love",
    },
]

export default Data;