export const events = [
  {
    id: 1,
    eventTitle: "Quaterly",
    prize: 1599,
    date: "2023-02-10",
    candidateList: [
      ["Candidate Name", "Voting Count"],
      ["Navnath", 1],
      ["Sneha", 5],
      ["Suman", 8],
      ["Omkar", 2],
      ["Rohit", 1],
      ["Rutuja", 8],
      ["Vaidehi", 1],
      ["Gaurav", 1],
      ["Akshay", 5],
      ["Nilesh", 6],
      ["Ajay", 2],
      ["Pranjal", 1],
      ["Sachin", 8],
      ["Sanjay", 1],
    ],
  },
  {
    id: 2,
    eventTitle: "Monthly",
    prize: 7999,
    date: "2023-02-10",
    candidateList: [
      ["Candidate Name", "Voting Count"],
      ["Rio", 9],
      ["Zeta", 1],
      ["Pushkar", 8],
      ["Gyan", 1],
      ["Ram", 3],
      ["Ketu", 1],
      ["Swanand", 5],
    ],
  },
  {
    id: 3,
    eventTitle: "Yearly",
    prize: 20000,
    date: "2023-02-06:17:56",
    candidateList: [
      ["Candidate Name", "Voting Count"],
      ["Nrupul", 1],
      ["Yogesh", 5],
      ["Reshma", 1],
      ["Supriya", 7],
      ["Kunal Prateek", 4],
      ["Sambit", 1],
      ["Raj", 2],
    ],
  },
  {
    id: 4,
    eventTitle: "Vollyball",
    prize: 6000,
    date: "2023-02-07",
    candidateList: [
      ["Candidate Name", "Voting Count"],
      ["Chintu", 19],
      ["Sonu", 5],
      ["Pinkku", 15],
      ["Chiku", 1],
      ["Rema", 1],
      ["Krish", 1],
      ["Ansh", 7],
    ],
  },
  {
    id: 5,
    eventTitle: "Football",
    prize: 4000,
    date: "2023-03-06",
    candidateList: [
      ["Candidate Name", "Voting Count"],
      ["Rakesh", 0],
      ["Vimal", 0],
    ],
  },
  {
    id: 6,
    eventTitle: "Cricket",
    prize: 9999,
    date: "2023-02-06:16:56",
    candidateList: [
      ["Candidate Name", "Voting Count"],
      ["Nilesh", 1],
      ["Akshay", 5],
      ["Aaksh", 8],
      ["Ajay", 1],
      ["Yogesh", 1],
      ["Praveen", 1],
      ["Vijay", 1],
    ],
  },
];

export const emploees = [
  {
    id: 1,
    fname: "Sneha",
    lname: "Gupta",
    email: "sneha@agsft.com",
    age: "22",
    empId: "AGS1011",
  },
  {
    id: 2,
    fname: "Rohit",
    lname: "Hiwrale",
    email: "rohit@agsft.com",
    age: "25",
    empId: "AGS1012",
  },
  {
    id: 3,
    fname: "Omkar",
    lname: "Ingawale",
    email: "omkar@agsft.com",
    age: "25",
    empId: "AGS1013",
  },
  {
    id: 4,
    fname: "Suman",
    lname: "Giri",
    email: "suman@agsft.com",
    age: "23",
    empId: "AGS1014",
  },
  {
    id: 5,
    fname: "Navnath",
    lname: "Borde",
    email: "navnath@agsft.com",
    age: "22",
    empId: "AGS1015",
  },
];
