// SHOW_LOADING
export const SHOW_LOADING = "SHOW_LOADING";

// SHOW_PRODUCTS
export const SHOW_PRODUCTS = "SHOW_PRODUCTS";

// SHOW_PRODUCT
export const SHOW_PRODUCT = "SHOW_PRODUCT";

// SHOW_CART_DETAILS
export const SHOW_CART_DETAILS = "SHOW_CART_DETAILS";

// UPDATE_CART_DETAILS
export const UPDATE_CART_DETAILS = "UPDATE_CART_DETAILS";

// DELETE_CART_DETAILS
export const DELETE_CART_DETAILS = "DELETE_CART_DETAILS";

// SHOW_ERROR
export const SHOW_ERROR = "SHOW_ERROR";